### ISSUE TITLE
Add (optional) Fediverse to member card.

### ISSUE THREAD

**Issue by MichalPorag** [urish/pull-request-community#38]
Add Fediverse to member card under social media's. 

What fediverse  is? https://en.wikipedia.org/wiki/Fediverse

**Comment by shir0206** [comment]
Please assign me

**Comment by MichalPorag** [comment]
@shir0206 
Hi, what's up? :) 
Do you had progress with that issue?
Do you need any help?

**Comment by idomand** [comment]
Hi @MichalPorag 
I would love to try and help out with this issue.

**Comment by idomand** [comment]
Hi 
There isn’t any one link to add because Fediverse is just the network of many sites that work with the same protocol. The biggest site in Fediverse right now is Mastodon that is a twitter copy.
 
I’ve added mastodon as an option for the personCard component as shown in this picture. Do you think that it’s enough?
![Capture](https://user-images.githubusercontent.com/63243268/115674348-3b292800-a356-11eb-93b0-5058ad55ccbb.JPG)
